"""Where the game, the prefab dump and the schemas live.

Nothing here is hardcoded to one machine: the game is found through Steam's
own library list, the dump is whatever `JWE3_<version>_Prefabs.lua` sits in the
game root, and anything detected wrongly can be overridden and is remembered in
`settings.json` beside the tool.
"""

from __future__ import annotations

import json
import os
import re

SETTINGS_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "settings.json"
)

GAME_FOLDER = "Jurassic World Evolution 3"
DUMP_PATTERN = re.compile(r"^JWE3_.*_Prefabs\.lua$", re.I)

# How the dump is produced, for the message shown when there isn't one.
DUMP_HELP = (
    "No prefab dump found in the game root.\n\n"
    "The dump is not shipped - it is generated by the game itself:\n"
    "  1. install ACSE and ACSEDebug\n"
    "  2. load into a park\n"
    "  3. open the ACSEDebug console and run:  LoadFile dump_all_prefabs\n\n"
    "It writes JWE3_<version>_Prefabs.lua into the game root (the folder\n"
    "holding JWE3.exe).  The script lives in Dev/Lua/dump_all_prefabs.lua."
)


def steam_libraries() -> list[str]:
    """Every Steam library folder, from Steam's own libraryfolders.vdf."""
    roots = [
        os.path.join(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"), "Steam"),
        os.path.join(os.environ.get("ProgramFiles", r"C:\Program Files"), "Steam"),
    ]
    found: list[str] = []
    for root in roots:
        vdf = os.path.join(root, "steamapps", "libraryfolders.vdf")
        if not os.path.exists(vdf):
            continue
        try:
            text = open(vdf, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for match in re.finditer(r'"path"\s*"([^"]+)"', text):
            path = match.group(1).replace("\\\\", "\\")
            if path not in found:
                found.append(path)
    for root in roots:
        if os.path.isdir(root) and root not in found:
            found.append(root)
    return found


def detect_game_root() -> str | None:
    for library in steam_libraries():
        candidate = os.path.join(library, "steamapps", "common", GAME_FOLDER)
        if os.path.isfile(os.path.join(candidate, "JWE3.exe")):
            return candidate
    return None


def dumps_in(game_root: str) -> list[str]:
    """Every prefab dump in the game root, newest version first."""
    if not game_root or not os.path.isdir(game_root):
        return []
    names = sorted((f for f in os.listdir(game_root) if DUMP_PATTERN.match(f)),
                   reverse=True)
    return [os.path.join(game_root, n) for n in names]


def detect_specdefs() -> tuple[str | None, str | None]:
    """The kit's extracted specdefs and enumnamers, if they are where we expect.

    Both ship inside GameMain/Main.ovl; the kit keeps an extracted copy.
    """
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    kit = os.path.dirname(os.path.dirname(here))       # ... / Main Mod Kit
    base = os.path.join(kit, "JWE 3 Luas", "Base Game", "GameMain")
    specs = os.path.join(base, "Specdefs")
    enums = os.path.join(base, "Enumnamer")
    return (specs if os.path.isdir(specs) else None,
            enums if os.path.isdir(enums) else None)


def detect_cobra() -> str | None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    kit = os.path.dirname(os.path.dirname(here))
    candidate = os.path.join(kit, "Cobra Dev", "cobra-tools-master")
    return candidate if os.path.isdir(candidate) else None


class Settings:
    """Detected defaults, overridable, remembered between runs."""

    def __init__(self) -> None:
        self.game_root: str | None = None
        self.dump_path: str | None = None
        self.specdef_dir: str | None = None
        self.enumnamer_dir: str | None = None
        self.load()

    # -- persistence -----------------------------------------------------
    def load(self) -> None:
        stored: dict = {}
        if os.path.exists(SETTINGS_FILE):
            try:
                stored = json.load(open(SETTINGS_FILE, encoding="utf-8"))
            except (OSError, ValueError):
                stored = {}
        self.game_root = stored.get("game_root") or detect_game_root()
        dumps = dumps_in(self.game_root or "")
        self.dump_path = stored.get("dump_path") or (dumps[0] if dumps else None)
        specs, enums = detect_specdefs()
        self.specdef_dir = stored.get("specdef_dir") or specs
        self.enumnamer_dir = stored.get("enumnamer_dir") or enums

    def save(self) -> None:
        try:
            with open(SETTINGS_FILE, "w", encoding="utf-8") as handle:
                json.dump({
                    "game_root": self.game_root,
                    "dump_path": self.dump_path,
                    "specdef_dir": self.specdef_dir,
                    "enumnamer_dir": self.enumnamer_dir,
                }, handle, indent=2)
        except OSError:
            pass

    # -- derived ---------------------------------------------------------
    @property
    def request_file(self) -> str | None:
        if not self.game_root:
            return None
        return os.path.join(self.game_root, "Dev", "Lua", "vlbridge_req.lua")

    @property
    def log_file(self) -> str | None:
        if not self.game_root:
            return None
        return os.path.join(self.game_root, "Jurassic World Evolution 3.log")

    def problems(self) -> list[str]:
        """Everything that would stop the tool working, in plain words."""
        issues: list[str] = []
        if not self.game_root:
            issues.append("Game folder not found. Set it in Settings.")
        elif not os.path.isfile(os.path.join(self.game_root, "JWE3.exe")):
            issues.append("That game folder has no JWE3.exe in it.")
        if not self.dump_path:
            issues.append(DUMP_HELP)
        elif not os.path.exists(self.dump_path):
            issues.append("The prefab dump no longer exists: %s" % self.dump_path)
        if not self.specdef_dir:
            issues.append("Specdefs folder not set - schema checks are off.")
        return issues


SETTINGS = Settings()
